package xyz.vmflow.vending.domain.payment

/**
 * Interface for pluggable payment processing providers.
 *
 * The vending app supports different payment backends through this abstraction.
 * Each provider implementation handles the specifics of payment authorization,
 * tokenization, and settlement for a particular payment system.
 *
 * ## Implementations
 * - [MockPaymentProvider]: Always-succeeding mock for development and testing.
 * - Future: Stripe, Square, PayPal, PIX, etc.
 *
 * ## Usage in Vending Flow
 * After receiving a vend request (0x0A) from the machine, the app calls
 * [processPayment] to authorize the payment before sending the credit
 * request to the backend.
 */
interface PaymentProvider {

    /**
     * Processes a payment for the given amount.
     *
     * This is called after a vend request is received from the machine and
     * the user confirms the purchase. The implementation should handle all
     * payment-specific logic (e.g., card tokenization, wallet authorization).
     *
     * @param amount The payment amount in the currency's main unit (e.g., 1.50 for $1.50).
     * @param currency The ISO 4217 currency code (e.g., "USD", "BRL").
     * @return A [PaymentResult] indicating success, failure, or cancellation.
     */
    suspend fun processPayment(amount: Double, currency: String): PaymentResult

    /**
     * Checks whether this payment provider is currently available.
     *
     * Used to determine if the provider can accept payments (e.g., is the
     * payment SDK initialized, is the user authenticated with the provider).
     *
     * @return `true` if the provider is ready to process payments.
     */
    fun isAvailable(): Boolean
}

/**
 * Result of a payment processing attempt.
 *
 * Represents the three possible outcomes of calling [PaymentProvider.processPayment].
 */
sealed class PaymentResult {

    /**
     * Payment was successfully authorized.
     *
     * @property transactionId A unique identifier for this transaction,
     *                         generated by the payment provider.
     */
    data class Success(val transactionId: String) : PaymentResult()

    /**
     * Payment failed due to an error.
     *
     * @property reason A human-readable description of why the payment failed
     *                  (e.g., "Insufficient funds", "Card declined").
     */
    data class Failure(val reason: String) : PaymentResult()

    /**
     * Payment was cancelled by the user before completion.
     */
    data object Cancelled : PaymentResult()
}
