/**
 * /api/devices
 *
 * GET  - List all ESP32 devices owned by the authenticated user.
 * POST - Register a new ESP32 device.
 *
 * Both operations are scoped to the authenticated user via Supabase RLS.
 * The passkey and subdomain are auto-generated by PostgreSQL defaults
 * (see the `embedded` table definition in the migration).
 */

import { NextRequest, NextResponse } from "next/server";
import { verifyAuth } from "@/lib/supabase/middleware";
import { createAuthClient } from "@/lib/supabase/client";

/**
 * GET /api/devices
 *
 * Returns all embedded devices owned by the authenticated user.
 * RLS ensures only the user's own devices are visible.
 *
 * Response (200):
 *   [{ id, subdomain, passkey, mac_address, status, status_at, created_at }]
 */
export async function GET(request: NextRequest) {
  const auth = await verifyAuth(request);
  if (!auth.ok) return auth.data.error;

  const supabase = createAuthClient(auth.data.authHeader);

  const { data, error } = await supabase
    .from("embedded")
    .select("id, subdomain, passkey, mac_address, status, status_at, created_at, machine_id")
    .order("created_at", { ascending: false });

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json(data);
}

/**
 * POST /api/devices
 *
 * Registers a new ESP32 embedded device.
 *
 * Request body:
 *   { mac_address?: string }
 *
 * The `subdomain` is auto-generated as an identity column, and the
 * `passkey` is auto-generated from a random MD5 hash (first 18 chars).
 * The `owner_id` is automatically set by the RLS default `auth.uid()`.
 *
 * Response (201):
 *   { id, subdomain, passkey, mac_address, status, created_at }
 */
export async function POST(request: NextRequest) {
  const auth = await verifyAuth(request);
  if (!auth.ok) return auth.data.error;

  try {
    const body = await request.json();
    const supabase = createAuthClient(auth.data.authHeader);

    const insertData: Record<string, unknown> = {};
    if (body.mac_address) {
      insertData.mac_address = body.mac_address;
    }

    const { data, error } = await supabase
      .from("embedded")
      .insert([insertData])
      .select("id, subdomain, passkey, mac_address, status, created_at")
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(data, { status: 201 });
  } catch {
    return NextResponse.json(
      { error: "Invalid request body" },
      { status: 400 }
    );
  }
}
