-- ============================================================
-- Panama Vending Machines - Initial Schema
-- ============================================================
-- Creates all tables, enums, RLS policies, and realtime config
-- for the vending machine backend.
-- ============================================================

-- ── Enum Types ──────────────────────────────────────────────

CREATE TYPE "public"."embedded_status" AS ENUM ('online', 'offline');

CREATE TYPE "public"."metric_name" AS ENUM ('paxcounter');

CREATE TYPE "public"."metric_unit" AS ENUM ('-');

CREATE TYPE "public"."sale_channel" AS ENUM ('ble', 'mqtt', 'cash');


-- ── Tables ──────────────────────────────────────────────────

-- Machine models (templates for machine types)
CREATE TABLE IF NOT EXISTS "public"."machine_models" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT "machine_models_pkey" PRIMARY KEY ("id")
);

-- Model coils (slot definitions per model)
CREATE TABLE IF NOT EXISTS "public"."model_coils" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    "model_id" uuid DEFAULT gen_random_uuid(),
    "alias" smallint,
    "item_number" smallint,
    CONSTRAINT "model_coils_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "model_coils_model_id_fkey" FOREIGN KEY ("model_id") REFERENCES "public"."machine_models"("id")
);

-- Machines (physical vending machines)
CREATE TABLE IF NOT EXISTS "public"."machines" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    "owner_id" uuid DEFAULT auth.uid(),
    "serial_number" text,
    "name" text,
    "refilled_at" timestamptz DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "machine_pkey" PRIMARY KEY ("id")
);

-- Embedded devices (ESP32 controllers inside machines)
CREATE TABLE IF NOT EXISTS "public"."embedded" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    "owner_id" uuid DEFAULT auth.uid(),
    "machine_id" uuid,
    "subdomain" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "mac_address" text,
    "status" "public"."embedded_status" DEFAULT 'offline' NOT NULL,
    "status_at" timestamptz DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
    "passkey" text DEFAULT substring(md5(random()::text) FROM 1 FOR 18) NOT NULL,
    CONSTRAINT "embeddeds_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "embedded_machine_id_key" UNIQUE ("machine_id"),
    CONSTRAINT "embedded_machine_id_fkey" FOREIGN KEY ("machine_id") REFERENCES "public"."machines"("id")
);

-- Machine coils (slot inventory per machine)
CREATE TABLE IF NOT EXISTS "public"."machine_coils" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    "product_id" uuid,
    "alias" smallint,
    "capacity" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "machine_coils_pkey" PRIMARY KEY ("id")
);

-- Products
CREATE TABLE IF NOT EXISTS "public"."products" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    "name" text,
    "barcode" text,
    "owner_id" uuid DEFAULT auth.uid() NOT NULL,
    CONSTRAINT "product_pkey" PRIMARY KEY ("id")
);

-- Sales (transactions)
CREATE TABLE IF NOT EXISTS "public"."sales" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    "embedded_id" uuid NOT NULL,
    "machine_id" uuid,
    "product_id" uuid,
    "item_price" double precision DEFAULT 0 NOT NULL,
    "item_number" bigint DEFAULT 0 NOT NULL,
    "channel" "public"."sale_channel" NOT NULL,
    "owner_id" uuid DEFAULT auth.uid(),
    "lat" double precision,
    "lng" double precision,
    CONSTRAINT "sale_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "sales_embedded_id_fkey" FOREIGN KEY ("embedded_id") REFERENCES "public"."embedded"("id"),
    CONSTRAINT "sale_machine_id_fkey" FOREIGN KEY ("machine_id") REFERENCES "public"."machines"("id"),
    CONSTRAINT "sale_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id")
);

-- Payments (placeholder for future payment integration)
CREATE TABLE IF NOT EXISTS "public"."payments" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);

-- Metrics (time-series, partitioned by year range)
CREATE TABLE IF NOT EXISTS "public"."metrics" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    "machine_id" uuid,
    "name" "public"."metric_name",
    "unit" "public"."metric_unit" DEFAULT '-',
    "value" real,
    "payload" jsonb,
    "embedded_id" uuid
) PARTITION BY RANGE ("created_at");

-- Metrics partition: 2026-2036
CREATE TABLE IF NOT EXISTS "public"."metrics_2026_2036" PARTITION OF "public"."metrics"
    FOR VALUES FROM ('2026-01-01') TO ('2036-01-01');


-- ── Row Level Security ──────────────────────────────────────

ALTER TABLE "public"."embedded" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."machines" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."sales" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."machine_coils" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."machine_models" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."model_coils" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."payments" ENABLE ROW LEVEL SECURITY;

-- SELECT policies: users can only see their own data
CREATE POLICY "select_policy" ON "public"."embedded"
    FOR SELECT TO authenticated
    USING (auth.uid() = owner_id);

CREATE POLICY "select_policy" ON "public"."machines"
    FOR SELECT TO authenticated
    USING (auth.uid() = owner_id);

CREATE POLICY "select_policy" ON "public"."products"
    FOR SELECT TO authenticated
    USING (auth.uid() = owner_id);

CREATE POLICY "select_policy" ON "public"."sales"
    FOR SELECT TO authenticated
    USING (auth.uid() = owner_id);

-- INSERT policies: authenticated users can insert
CREATE POLICY "insert_policy" ON "public"."embedded"
    FOR INSERT TO authenticated
    WITH CHECK (true);

CREATE POLICY "insert_policy" ON "public"."machines"
    FOR INSERT TO authenticated
    WITH CHECK (true);

CREATE POLICY "insert_policy" ON "public"."products"
    FOR INSERT TO authenticated
    WITH CHECK (true);

CREATE POLICY "insert_policy" ON "public"."sales"
    FOR INSERT TO authenticated
    WITH CHECK (true);

-- UPDATE policies
CREATE POLICY "update_policy" ON "public"."machines"
    FOR UPDATE TO authenticated
    USING (true)
    WITH CHECK (auth.uid() = owner_id);


-- ── Realtime ────────────────────────────────────────────────

ALTER PUBLICATION supabase_realtime ADD TABLE ONLY "public"."sales";
